### ISSUE TITLE
latest release breaks Cucumber

### ISSUE THREAD

**Issue by samhatoum** [Sanjo/meteor-long-running-child-process#7]
`log.setLevel was called with an invalid level` - or similar

I had to add a package called `xolvio:env-set@0.0.2` that sets `process.env.LONG_RUNNING_CHILD_PROCESS_LOG_LEVEL='info'` before this package is loaded as a temporary fix.

I think [this line](https://github.com/Sanjo/meteor-long-running-child-process/commit/249aa0c9c8a86fd6496959c818182e08b3adce60#diff-c5660c377ba6a10a7a6b0845bd61453aR154) is correctly setting to a default

**Comment by Sanjo** [comment]
Already fixed ;-) 1.1.3

**Comment by Sanjo** [comment]
https://github.com/Sanjo/meteor-long-running-child-process/commit/5951f640ac63213cd99e1fae558269640a06c6e6
